# Generated by Django 3.1.2 on 2021-07-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('FullName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=50)),
                ('FacilityCode', models.CharField(max_length=100)),
                ('EmployerNo', models.CharField(max_length=100)),
                ('TelephoneNo', models.CharField(max_length=100)),
                ('EmailAddress', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
